name: Create Issue

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Github Issue
        run: |
            curl \
            --request POST \
            --url "https://api.github.com/repos/xrabcde/issue-test/issues" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer  ${{secrets.TOKEN}}" \
            --data '{
              "title": "[공지] 에러 TEST",
              "body": "브라우징 에러",
              "labels":["bug"]
            }'
